class Event(object):
    """
    Represents a calendar event with all its properties.
    This class stores information about a single calendar event including
    timing details, description, and recurrence status.
    Attributes:
        event_id (int): Unique identifier for the event (auto-generated by database)
        title (str): The title/name of the event
        date (str): The primary date of the event in YYYY-MM-DD format
        start_day (str): The starting date of the event in YYYY-MM-DD format
        end_day (str): The ending date of the event in YYYY-MM-DD format
        start_time (str): The start time of the event
        end_time (str): The end time of the event
        description (str): Detailed description of the event
        is_recurring (bool): Whether the event repeats regularly
        recurrence_pattern (str): How often the event repeats (daily, weekly, monthly, yearly)
        is_all_day (bool): Whether the event is an all-day event
    """
    def __init__(self, event_id, title, date, start_day, end_day, start_time, end_time, description, is_recurring, recurrence_pattern=None, is_all_day=False):
        """
        Initialize an Event object with all necessary properties.
        Args:
            event_id (int or None): Unique identifier for the event (None for new events)
            title (str): The title/name of the event
            date (str): The primary date when the event occurs (YYYY-MM-DD)
            start_day (str): The starting day of the event (YYYY-MM-DD)
            end_day (str): The ending day of the event (YYYY-MM-DD)
            start_time (str): The time when the event starts
            end_time (str): The time when the event ends
            description (str): Detailed description of what the event is about
            is_recurring (bool): True if the event repeats, False for one-time events
            recurrence_pattern (str, optional): How often the event repeats (e.g., "daily", "weekly", "monthly", "yearly")
            is_all_day (bool, optional): True if the event is an all-day event, False for timed events
        """
        self._event_id = event_id
        self._title = title
        self._date = date
        self._start_day = start_day
        self._end_day = end_day
        self._start_time = start_time
        self._end_time = end_time
        self._description = description
        self._is_recurring = is_recurring
        self._recurrence_pattern = recurrence_pattern
        self._is_all_day = is_all_day

    # Event ID property
    @property
    def event_id(self):
        """Get the event ID."""
        return self._event_id

    @event_id.setter
    def event_id(self, value):
        """Set the event ID."""
        if value is not None and not isinstance(value, int):
            raise TypeError("Event ID must be an integer or None")
        self._event_id = value

    # Title property
    @property
    def title(self):
        """Get the event title."""
        return self._title

    @title.setter
    def title(self, value):
        """Set the event title."""
        if not isinstance(value, str):
            raise TypeError("Title must be a string")
        if not value.strip():
            raise ValueError("Title cannot be empty")
        self._title = value

    # Date property
    @property
    def date(self):
        """Get the event date."""
        return self._date

    @date.setter
    def date(self, value):
        """Set the event date."""
        if not isinstance(value, str):
            raise TypeError("Date must be a string")
        if not value.strip():
            raise ValueError("Date cannot be empty")
        self._date = value

    # Start day property
    @property
    def start_day(self):
        """Get the start day."""
        return self._start_day

    @start_day.setter
    def start_day(self, value):
        """Set the start day."""
        self._start_day = value

    # End day property
    @property
    def end_day(self):
        """Get the end day."""
        return self._end_day

    @end_day.setter
    def end_day(self, value):
        """Set the end day."""
        self._end_day = value

    # Start time property
    @property
    def start_time(self):
        """Get the start time."""
        return self._start_time

    @start_time.setter
    def start_time(self, value):
        """Set the start time."""
        if not isinstance(value, str):
            raise TypeError("Start time must be a string")
        self._start_time = value

    # End time property
    @property
    def end_time(self):
        """Get the end time."""
        return self._end_time

    @end_time.setter
    def end_time(self, value):
        """Set the end time."""
        if not isinstance(value, str):
            raise TypeError("End time must be a string")
        self._end_time = value

    # Description property
    @property
    def description(self):
        """Get the event description."""
        return self._description

    @description.setter
    def description(self, value):
        """Set the event description."""
        if not isinstance(value, str):
            raise TypeError("Description must be a string")
        self._description = value

    # Is recurring property
    @property
    def is_recurring(self):
        """Get whether the event is recurring."""
        return self._is_recurring

    @is_recurring.setter
    def is_recurring(self, value):
        """Set whether the event is recurring."""
        if not isinstance(value, bool):
            raise TypeError("is_recurring must be a boolean")
        self._is_recurring = value

    # Recurrence pattern property
    @property
    def recurrence_pattern(self):
        """Get the recurrence pattern."""
        return self._recurrence_pattern

    @recurrence_pattern.setter
    def recurrence_pattern(self, value):
        """Set the recurrence pattern."""
        if value is not None and not isinstance(value, str):
            raise TypeError("Recurrence pattern must be a string or None")
        self._recurrence_pattern = value

    # Is all day property
    @property
    def is_all_day(self):
        """Get whether the event is all day."""
        return self._is_all_day

    @is_all_day.setter
    def is_all_day(self, value):
        """Set whether the event is all day."""
        if not isinstance(value, bool):
            raise TypeError("is_all_day must be a boolean")
        self._is_all_day = value

    @classmethod
    def from_dict(cls, event_dict):
        """
        Create an Event object from a dictionary (e.g., from database).
        This is a factory method that the Event class uses to create itself.

        Args:
            event_dict (dict): Dictionary containing event data with keys:
                - event_id, title, date, start_day, end_day,
                - start_time, end_time, description, is_recurring,
                - recurrence_pattern, is_all_day

        Returns:
            Event: A new Event object created from the dictionary

        Example:
            event = Event.from_dict({
                'event_id': 1,
                'title': 'Meeting',
                'date': '2025-11-22',
                ...
            })
        """
        return cls(
            event_id=event_dict['event_id'],
            title=event_dict['title'],
            date=event_dict['date'],
            start_day=event_dict['start_day'],
            end_day=event_dict['end_day'],
            start_time=event_dict['start_time'],
            end_time=event_dict['end_time'],
            description=event_dict.get('description', ''),
            is_recurring=event_dict.get('is_recurring', False),
            recurrence_pattern=event_dict.get('recurrence_pattern'),
            is_all_day=event_dict.get('is_all_day', False)
        )

    @classmethod
    def create_new(cls, title, date, start_time="", end_time="", 
                   description="", is_all_day=False, is_recurring=False, 
                   recurrence_pattern=None):
        """
        Create a new Event object (without event_id - will be assigned by database).
        This is a factory method for creating new events before they're saved.

        Args:
            title (str): Event title
            date (str): Event date in YYYY-MM-DD format
            start_time (str): Start time (optional for all-day events)
            end_time (str): End time (optional for all-day events)
            description (str): Event description
            is_all_day (bool): Whether this is an all-day event
            is_recurring (bool): Whether this event repeats
            recurrence_pattern (str): How the event repeats (if recurring)

        Returns:
            Event: A new Event object ready to be saved

        Example:
            event = Event.create_new(
                title="Team Meeting",
                date="2025-11-22",
                start_time="10:00 AM",
                end_time="11:00 AM"
            )
        """
        return cls(
            event_id=None,  # Will be assigned by database
            title=title,
            date=date,
            start_day=date,  # For single-day events, same as date
            end_day=date,    # For single-day events, same as date
            start_time=start_time,
            end_time=end_time,
            description=description,
            is_recurring=is_recurring,
            recurrence_pattern=recurrence_pattern,
            is_all_day=is_all_day
        )

    def to_dict(self):
        """
        Convert this Event object to a dictionary.
        Useful for database operations and serialization.

        Returns:
            dict: Dictionary representation of the event

        Example:
            event_dict = event.to_dict()
            # Can be used with database operations
        """
        return {
            'event_id': self.event_id,
            'title': self.title,
            'date': self.date,
            'start_day': self.start_day,
            'end_day': self.end_day,
            'start_time': self.start_time,
            'end_time': self.end_time,
            'description': self.description,
            'is_recurring': self.is_recurring,
            'recurrence_pattern': self.recurrence_pattern,
            'is_all_day': self.is_all_day
        }